name: PlayQ_code_build_and_deploy
env:
  S3_BUCKET_NAME: "playq-exercise-artifact"
  AWS_REGION_NAME: "eu-central-1"
  PROGRAM_NAME: "playq"
  WALL_PARAMETER: "-Wall"

on:
  push:
    branches:
      - master

jobs:
  linux-job:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: g++ build
        run: |
          g++ ${{ env.WALL_PARAMETER }} -o ${{ env.PROGRAM_NAME }}-linux.bin code.cpp

      - name: Testing builded bin
        run: |
          echo foo | ./${{ env.PROGRAM_NAME }}-linux.bin >> test-linux.txt

      - name: Commit files
        run: |
          git config --local user.email "test@test.test"
          git config --local user.name "github-actions[bot]"
          git add test-linux.txt
          git commit -m "Upload tests results for linux"
     
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: outs

      - name: Upload actifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-linux
          path: |
            test-linux.txt

      - name: aws creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}

      - name: Copy bin to s3
        run: |
          aws s3 cp ./${{ env.PROGRAM_NAME }}-linux.bin s3://${{ env.S3_BUCKET_NAME }}/

  macos-job:
    runs-on: macos-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: g++ build
        run: |
          g++ ${{ env.WALL_PARAMETER }} -o ${{ env.PROGRAM_NAME }}-macos.bin code.cpp

      - name: Testing builded bin
        run: |
          echo foo | ./${{ env.PROGRAM_NAME }}-macos.bin >> test-macos.txt

      - name: Commit files
        run: |
          git config --local user.email "test@test.test"
          git config --local user.name "github-actions[bot]"
          git add test-macos.txt
          git commit -m "Upload tests results for macos"
     
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: outs

      - name: Upload actifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-macos
          path: |
            test-macos.txt
      
      - name: aws creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}

      - name: Copy bin to s3
        run: |
          aws s3 cp ./${{ env.PROGRAM_NAME }}-macos.bin s3://${{ env.S3_BUCKET_NAME }}/